import { afterEach, describe, expect, it, vi } from "vitest";
import { POST } from "@/app/api/collaboration/route";
const valid = { path: "technical", name: "Avery Lee", email: "avery@example.com", role: "technical_collaborator", message: "I would like to discuss a focused documentation contribution.", acknowledgement: true };
function post(body: unknown, ip = "10.2.1.1") { return POST(new Request("http://localhost/api/collaboration", { method: "POST", headers: { "content-type": "application/json", "x-forwarded-for": ip }, body: JSON.stringify(body) }) as any); }
describe("POST /api/collaboration", () => {
  afterEach(() => { vi.restoreAllMocks(); vi.unstubAllEnvs(); });
  it("delivers a complete fixed-schema inquiry through the configured webhook", async () => { vi.stubEnv("COLLABORATION_WEBHOOK_URL", "https://example.test/inbox"); vi.spyOn(global, "fetch").mockResolvedValue(new Response("", { status: 202 })); const response = await post(valid); expect(response.status).toBe(200); await expect(response.json()).resolves.toMatchObject({ success: true, requestId: expect.stringMatching(/^col_/) }); });
  it("does not claim delivery when no webhook is configured", async () => { const response = await post(valid, "10.2.1.8"); expect(response.status).toBe(503); });
  it("uses Resend to deliver to the configured inbox", async () => { vi.stubEnv("RESEND_API_KEY", "re_test"); vi.stubEnv("COLLABORATION_FROM_EMAIL", "Aarti Portfolio <collaboration@ai-aarti.com>"); vi.spyOn(global, "fetch").mockResolvedValue(new Response(JSON.stringify({ id: "email_1" }), { status: 200 })); const response = await post(valid, "10.2.1.9"); expect(response.status).toBe(200); expect(global.fetch).toHaveBeenCalledWith("https://api.resend.com/emails", expect.objectContaining({ method: "POST" })); });
  it("retries one timed-out Resend request with the same idempotency key", async () => { vi.stubEnv("RESEND_API_KEY", "re_test"); vi.stubEnv("COLLABORATION_FROM_EMAIL", "Aarti Portfolio <collaboration@ai-aarti.com>"); const fetch = vi.spyOn(global, "fetch").mockRejectedValueOnce(new DOMException("", "TimeoutError")).mockResolvedValueOnce(new Response(JSON.stringify({ id: "email_1" }), { status: 200 })); const response = await post(valid, "10.2.1.10"); expect(response.status).toBe(200); expect(fetch).toHaveBeenCalledTimes(2); const first = fetch.mock.calls[0][1] as RequestInit, second = fetch.mock.calls[1][1] as RequestInit; expect(first.headers).toEqual(second.headers); });
  it("rejects unsupported paths and missing acknowledgement", async () => { const response = await post({ ...valid, path: "sales", acknowledgement: false }); expect(response.status).toBe(400); await expect(response.json()).resolves.toMatchObject({ success: false, error: "Choose a collaboration path." }); });
  it("rate limits repeated inquiries", async () => { vi.stubEnv("COLLABORATION_WEBHOOK_URL", "https://example.test/inbox"); vi.spyOn(global, "fetch").mockResolvedValue(new Response("", { status: 202 })); for (let index = 0; index < 4; index += 1) expect((await post(valid, "10.2.1.2")).status).toBe(200); expect((await post(valid, "10.2.1.2")).status).toBe(429); });
});
